[package]
name = "ghdstats"
version = "1.3.0"
edition = "2024"

[profile.release]
strip = true
lto = true
panic = "abort"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0.140", features = ["derive"] }
