[package]
name = "ghdstats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
ureq = { version = "2.5.0", features = ["serde", "serde_json"] }
